name: build-redoubt-static-base

on:
  push:
    branches: [main]
    paths:
      - "images/static-base/**"
      - ".github/workflows/build-redoubt-static-base.yaml"
      - ".github/workflows/build-redoubt-image.yaml"
    tags:
      - "static-base/v*"
  pull_request:
    paths:
      - "images/static-base/**"
      - ".github/workflows/build-redoubt-static-base.yaml"
      - ".github/workflows/build-redoubt-image.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-redoubt-image.yaml
    with:
      image-name: static-base
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write