name: build-redoubt-golang

on:
  push:
    branches: [main]
    paths:
      - "images/golang/**"
      - ".github/workflows/build-redoubt-golang.yaml"
      - ".github/workflows/build-redoubt-image.yaml"
    tags:
      - "golang/v*"
  pull_request:
    paths:
      - "images/golang/**"
      - ".github/workflows/build-redoubt-golang.yaml"
      - ".github/workflows/build-redoubt-image.yaml"
  workflow_dispatch:

jobs:
  golang-build:
    uses: ./.github/workflows/build-redoubt-image.yaml
    with:
      image-name: golang-build
      dockerfile: Dockerfile.builder
      context: images/golang
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
  golang:
    uses: ./.github/workflows/build-redoubt-image.yaml
    with:
      image-name: golang
      dockerfile: Dockerfile.runtime
      context: images/golang
      production: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write